[package]
name = "dojohunt"
version = "1.0.0"

[addresses]
# This address will be overridden by --named-addresses during deployment
# For new deployments, use 0x0 (will be determined by publisher account)
# For upgrades, use the existing module address
dojohunt = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

